kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nutanix-volumes
provisioner: csi.nutanix.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-cluster-csi-drivers
  csi.storage.k8s.io/node-publish-secret-name: ntnx-secret
  csi.storage.k8s.io/node-publish-secret-namespace: openshift-cluster-csi-drivers
  csi.storage.k8s.io/controller-expand-secret-name: ntnx-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: openshift-cluster-csi-drivers
  csi.storage.k8s.io/fstype: ext4
  storageContainer: Default           
  storageType: NutanixVolumes
  isLVMVolume: "true"
  numLVMDisks: "4"
allowVolumeExpansion: true
reclaimPolicy: Delete
